#!/bin/bash

# how to use:
# in cmake-build-directoruy call 'cmt'
# its equal to call your build system with same targets
# if your build system is make, then 'cmt' is equal to 'make'
# 'cmt target' is equal to 'make target'

set -euo pipefail # exit if some target failed - i think is good idea

if [ $# -eq 0 ]; then
	cmake --build .
	exit 0
fi

for target in "$@"
do
	# cmake --build . --target t1 t2 ... - is not supported yet
	cmake --build . --target $target
done
