#!/bin/bash

# usage (in cmake build directory): 'cmake-deps'

# why Ninja

set -euo pipefail

if [ $# -eq 0 ]; then
	cmake_dir=".."
	build_dir=""
elif [ $# -eq 2 ]; then
	cmake_dir="$1"
	build_dir="$2"
else
	echo "Usage: $0 [<cmake dir> <build dir>]"
	exit 1
fi

dot_out_dir="$build_dir/dot-out"
dot_file="$dot_out_dir/dependencies.dot"
image_dir="$cmake_dir/assets"
image_file="$image_dir/dependencies.png"

if [ -n "$(find .. -name '*.cppm')" ]; then
	generator="Ninja"
	cxx_compiler="clang++"
else
	generator="Unix Makefiles"
	cxx_compiler="g++"
fi

mkdir -p "$image_dir"
rm -rf "$dot_out_dir"
cmake -S "$cmake_dir" -B "$build_dir" -G "$generator" -DCMAKE_CXX_COMPILER="$cxx_compiler" --graphviz="$dot_file"
dot -Tpng "$dot_file" -o "$image_file"
